# Generated by Django 3.1.4 on 2021-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlapi', '0002_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
    ]
