# Generated by Django 3.1.4 on 2021-02-21 20:55

from django.db import migrations


def add_languages(apps, schema_editor):
    Language = apps.get_model('vlapi', 'Language')

    spanish = Language(name='es')
    english = Language(name='en')

    Language.objects.bulk_create([spanish, english])


class Migration(migrations.Migration):

    dependencies = [
        ('vlapi', '0003_language'),
    ]

    operations = [
        migrations.RunPython(add_languages)
    ]
