# Generated by Django 3.1.4 on 2021-02-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlapi', '0005_unique_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(default='es', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='vlapi.language', to_field='name'),
            preserve_default=False,
        ),
    ]
